name: Matrix fun

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix: 
        fun-message: ["Hello", "potion", "seller", "🧪"]
    steps:
      - run: echo "${fun-message}"
  build2: 
   runs-on: macos-latest
   needs: 
     build 
   steps: 
     - run: echo "hi, build 1 must have finished"
