name: Matrix fun

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix: 
        fun-message: ["Hello", "potion", "seller", "🧪"]
    steps:
      - run: echo "${fun-message}"
