name: Slack Bot

on:
 push: 
   branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Notify slack on success or failure
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"C022V02HWRF\",\"text\":\"  ${{github.actor}} pushed to ${{GITHUB_REF##*/}}  \"}'
        
 
