name: Slack Bot

on:
  release:
    types: [created]
    
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Notify slack on success or failure
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"C022V02HWRF\",\"text\":\"Hello world\"}'
