name: Test exiting on failure

on:
  push: 
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Echo
      run: echo ${{matrix.os}}
    - name: condition 1
      run: echo "hi"
      if: matrix.os == 'ubuntu-latest'
    - name: Try to fail
      run: exit 1
    - name: Print message if we dont fail
      run: echo Should not get here





jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Dependencies (Linux)
      run: sudo apt-get install ninja-build
      if: matrix.os == 'ubuntu-latest'
    - name: Install Dependencies (Windows)
      run: choco install ninja
      if: matrix.os == 'windows-latest'
    - name: Install Dependencies (macOS)
      run: brew install ninja
      if: matrix.os == 'macos-latest'
    - name: Get Sources
      uses: actions/checkout@v1
    - name: Setup CMake
      run: |
        mkdir "${{ runner.workspace }}/build"
        cd "${{ runner.workspace }}/build"
        cmake $GITHUB_WORKSPACE -GNinja
      shell: bash
    - name: Build
      run: cmake --build .
      working-directory: ${{ runner.workspace }}/build      
    - name: Test
      run: ctest -V
      working-directory: ${{ runner.workspace }}/build
