name: Test exiting on failure

on:
  push: 
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Echo
      run: echo ${{matrix.os}}
    - name: condition 1
      if: matrix.os == ubuntu-latest
      run: "Condition 1 passed"
    - name: Try to fail
      run: exit 1
    - name: Print message if we don't fail
      run: echo Should not get here
