name: Test exiting on failure

on:
  push: 
    branches: [develop]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Echo
      run: echo ${{matrix.os}}
    - name: condition 1
      run: exit 1
      if: matrix.os == 'macOS-latest'
    - name: Valid OS
      run: echo "We are a valid os ${{ matrix.os }}"
