name: Unit Tests

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  run_workspace_Tests:
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 8']
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_12.2.app && /usr/bin/xcodebuild -version
      - name: Build and test
        run: bundle exec fastlane scan --destination "${destination}" --scheme "Github-Actions-Fun"
        env:
         destination: $
      - name: Run unit tests
        run: xcodebuild test -project Github-Actions-Fun/Github-Actions-Fun.xcodeproj -scheme Github-Actions-Fun -destination 'platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device'

