name: Unit Tests

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  run_workspace_Tests:
    runs-on: macOS-latest
    steps:
      - name: What can I even use
        run: instruments -s devices
      - uses: actions/checkout@v1
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_11.3.app
      - name: Run unit tests
        run: xcodebuild clean test -project "Github-Actions-Fun/Github-Actions-Fun.xcodeproj" -scheme "Github-Actions-Fun" -destination "platform=iOS Simulator,OS=14.4,name=iPhone 11 (14.4)"
