name: Unit Tests

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:

      runs-on: iOS-latest

      steps:
      - uses: actions/checkout@v1
      - name: Force Xcode 11
        run: sudo xcode-select -switch /Applications/Xcode_11.3.app
      - name: Run tests
        run: xcodebuild clean test -project "Github-Actions-Fun/Github-Actions-Fun.xcodeproj" -scheme "Github-Actions-Fun" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"
      - name: Build App
        run: xcodebuild -project "Github-Actions-Fun/Github-Actions-Fun.xcodeproj" -scheme "Github-Actions-Fun" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO

  run_workspace_Tests:
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 8']
    runs-on: macOS-latest
    steps:
      - name: What can I even use
        run: instruments -s devices
      - uses: actions/checkout@v1
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_11.3.app
      - name: Run unit tests
        run: xcodebuild clean test -project "Github-Actions-Fun/Github-Actions-Fun.xcodeproj" -scheme "Github-Actions-Fun" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"

